# Use an official Golang runtime as a parent image
FROM golang:1.16

# Set the working directory to /pkg
WORKDIR /pkg

# Copy the current directory contents into the container at /app
COPY . /pkg

# Install any needed packages specified in go.mod
RUN go mod download

# Build the Go app
RUN go build -o main .

# Expose port 8000 for the container
EXPOSE 8000

# Define the command to run the executable
CMD ["/pkg/main"]